### ISSUE TITLE
Notes when upgrading to ubuntu 18

### ISSUE THREAD

**Issue by tiago-loureiro** [wireapp/ansible-cassandra#10]
This ansible role has been tested on ubuntu 16, but it'd be useful to already have some ideas on what may/will break with ubuntu 18. This is the feedback from one user:

> roles-external/ansible-role-java/vars/Ubuntu-18.yml
> - openjdk-11-jdk
> =>
> - openjdk-8-jdk
> (servers are Ubuntu 18.04, and Cassandra 3.11 is only compatible with Java 8)

**Comment by jschaul** [comment]
Yes, this is done in the travis/molecule tests here: 

https://github.com/wireapp/ansible-cassandra/blob/master/molecule/default/playbook.yml#L12-L15

But perhaps should be better documented in the readme, and this variable set in wire-server-deploy.

**Comment by julialongtin** [comment]
Addressed with PR #12
